DROP TABLE EMP_BOARDS CASCADE CONSTRAINTS;
DROP SEQUENCE EMP_BOARDS_SEQ;

CREATE TABLE EMP_BOARDS (
	   ID NUMBER NOT NULL
	 , TITLE VARCHAR2(100) NOT NULL
	 , CONTENT VARCHAR2(2000)
	 , EMPID NUMBER NOT NULL
	 , CREATEDATE DATE DEFAULT(SYSDATE)
	 , VIEW_CNT NUMBER DEFAULT(0)
	 , "LIKE" NUMBER DEFAULT(0)
	 , CONSTRAINT EMP_BOARDS_ID_PK PRIMARY KEY (ID)
	 , CONSTRAINT EMP_BOARDS_EMPID_FK FOREIGN KEY(EMPID) REFERENCES EMPLOYEES(EMPLOYEE_ID)
);


-- 게시판 글을 등록하기 전에 ID 번호를 자동 생성하여 가져오기 위한 쿼리
SELECT EMP_BOARDS_SEQ.NEXTVAL FROM DUAL
-- 게시판 글을 등록하기 위한 쿼리
INSERT INTO EMP_BOARDS(ID, TITLE, CONTENT, EMPID, CREATEDATE)
     VALUES(1,'여기에 제목을 넣으세요', '여기에 내용을 넣으세요', 100, SYSDATE)
