/*
* EMPLOYEES 테이블의 구조를 복사한 새로운 테이블 2개를 생성.
* 		1. EMP_COMMISSION 테이블을 만든다. - 테이블은 EMP_ID , FIRST_NAME, LAST_NAME, SALARY, COMMISSION_PCT 컬럼을 가진다
*		2. EMP_NO_COMMISSION 테이블은 만든다. - 테이블은 EMP_ID , FIRST_NAME, LAST_NAME, SALARY 컬럼을 가진다.
*/
CREATE TABLE EMP_COMMISSION
	AS SELECT EMPLOYEE_ID
			 ,FIRST_NAME
			 ,LAST_NAME
			 ,SALARY
			 ,COMMISSION_PCT
		FROM EMPLOYEES
		WHERE 1= 0;

CREATE TABLE EMP_NO_COMMISSION
	AS SELECT EMPLOYEE_ID
			 ,FIRST_NAME
			 ,LAST_NAME
			 ,SALARY
		FROM EMPLOYEES
		WHERE 1= 0;	
	
SELECT * FROM EMP_COMMISSION;
SELECT * FROM EMP_NO_COMMISSION;
/*
 * 위 작업을 통해 생성한 테이블에 EMPLOYEE 테이블이 가지고 있는 모든 행 데이터를 추가.
 * 	INSERT INTO ... (SELECT ... 구문을 사용하여 추가해 본다.)
 *  INSERT ALL INTO ... 구문을 사용하여 추가해 본다.
 * 
 * 
 * 위 작업을 진행 할 때 DELETE FROM EMP_COMMISSION, DELETE FROM EMP_NO_COMMISSION; 을 작업 후 진행한다. 
 */

DELETE FROM EMP_COMMISSION;
DELETE FROM EMP_NO_COMMISSION;


INSERT INTO EMP_COMMISSION(
			SELECT EMPLOYEE_ID
				  ,FIRST_NAME
				  ,LAST_NAME
				  ,SALARY
				  ,COMMISSION_PCT
				  FROM EMPLOYEES
				  WHERE COMMISSION_PCT IS NOT NULL
);

INSERT INTO EMP_NO_COMMISSION(
			SELECT EMPLOYEE_ID
				  ,FIRST_NAME
				  ,LAST_NAME
				  ,SALARY
				  FROM EMPLOYEES
				  WHERE COMMISSION_PCT IS  NULL
);

DELETE FROM EMP_COMMISSION;
DELETE FROM EMP_NO_COMMISSION;

INSERT ALL
 WHEN COMMISSION_PCT IS NOT NULL THEN 
  	  INTO EMP_COMMISSION VALUES (EMPLOYEE_ID, FIRST_NAME, 이름, SALARY, COMMISSION_PCT)
 WHEN COMMISSION_PCT IS NULL THEN 
  	  INTO EMP_NO_COMMISSION VALUES(EMPLOYEE_ID, FIRST_NAME, 이름, SALARY)
SELECT EMPLOYEE_ID, LOWER(FIRST_NAME) AS FIRST_NAME, LOWER(LAST_NAME) AS 이름, SALARY, COMMISSION_PCT
  FROM EMPLOYEES;

 SELECT *FROM EMP_COMMISSION;
 SELECT *FROM EMP_NO_COMMISSION;

/*
 * EMP_COMMISSION 테이블에서 모든 사원에 대해 COMMISSOIN_PCT 를 0.02 증가
 */
UPDATE EMP_COMMISSION
	SET COMMISSION_PCT =  COMMISSION_PCT + 0.02;
 SELECT *FROM EMP_COMMISSION;
COMMIT;

/*
 * EMP_NO_COMMISSION 테이블에서 SALARY 가 4000 이하인 사원들에 대해 SALARY 를 200 증가
 */

UPDATE EMP_NO_COMMISSION
	SET SALARY = SALARY + 200
WHERE SALARY <= 4000;

COMMIT;



UPDATE EMP_COMMISSION
  SET SALARY = SALARY + 100
WHERE EMPLOYEE_ID IN (SELECT MANAGER_ID FROM DEPARTMENTS WHERE MANAGER_ID IS NOT NULL);  

UPDATE EMP_NO_COMMISSION
  SET SALARY = SALARY + 100
WHERE EMPLOYEE_ID IN (SELECT MANAGER_ID FROM DEPARTMENTS WHERE MANAGER_ID IS NOT NULL);  

COMMIT;


