-- 직원 테이블
SELECT *  
	FROM EMPLOYEES; 

SELECT EMPLOYEE_ID
	,FIRST_NAME
	,LAST_NAME
 FROM EMPLOYEES;	

SELECT EMPLOYEE_ID 
	, FIRST_NAME 
	, LAST_NAME
 FROM EMPLOYEES
 WHERE EMPLOYEE_ID >= 200;

 
 SELECT EMPLOYEE_ID 
	, FIRST_NAME 
	, LAST_NAME
 FROM EMPLOYEES
 WHERE EMPLOYEE_ID >= 200
   AND FIRST_NAME = 'Pat';
  
 SELECT EMPLOYEE_ID 
	, FIRST_NAME 
	, LAST_NAME
 FROM EMPLOYEES
 WHERE EMPLOYEE_ID >= 200
   OR FIRST_NAME = 'Steven';
 
  /*
   * 문자열 리터럴은 작은따옴표 ''
   * 
   * 별칭은 쌍따옴표 ""
   */
  
SELECT EMPLOYEE_ID AS "사번"
	, FIRST_NAME AS 이름
	, LAST_NAME 성
	, EMAIL "이메일 주소"
 FROM EMPLOYEES;


SELECT EMPLOYEE_ID AS "사번"
	,FIRST_NAME AS "이름"
	,LAST_NAME AS "성"
	FROM EMPLOYEES
	WHERE EMPLOYEE_ID >= 200;
/*
 * 순서 FROM -> WHERE -> SELECT
 */

/*
 * 문자열 결합 
 */
SELECT FIRST_NAME || ' ' || LAST_NAME AS "이름"
	, SALARY * 12 AS "연봉"
FROM EMPLOYEES;


-- 조건절에서 사용하는 연산자
-- AND, OR, NOT, IN, NOT IN, BETWEEN ...AND 
-- LIKE, NOT LIKE, IS NULL, IS NOT NULL 
SELECT *
  FROM EMPLOYEES
  WHERE NOT EMPLOYEE_ID >= 200;
 
 SELECT *
 FROM EMPLOYEES
 WHERE EMPLOYEE_ID IN (200,201,202,203); --특정값 조회

 SELECT *
 FROM EMPLOYEES
 WHERE EMPLOYEE_ID NOT IN (200,201,202,203); --빼고 조회

 SELECT *
 FROM EMPLOYEES
 WHERE EMPLOYEE_ID BETWEEN 200 AND 203; --사이

 SELECT *
 FROM EMPLOYEES
 WHERE FIRST_NAME LIKE 'S%'; --로 시작하는 이름

 SELECT *
 FROM EMPLOYEES
 WHERE FIRST_NAME LIKE '%en'; --en으로 끝나는 이름
 
 SELECT *
 FROM EMPLOYEES
 WHERE FIRST_NAME LIKE '%ea%'; --ea가 포함된 이름
 
 SELECT *
 FROM EMPLOYEES
 WHERE FIRST_NAME LIKE '_____'; -- 5글자 이름 
 
 SELECT *
 FROM EMPLOYEES
 WHERE FIRST_NAME LIKE 'D____';-- 대문자 포함 나머지 글자수
 
 SELECT *
 FROM EMPLOYEES
 WHERE JOB_ID LIKE '%\____' ESCAPE '\'; --이스케이프문자

 SELECT *
 FROM EMPLOYEES
 WHERE JOB_ID NOT LIKE '%\____' ESCAPE '\'; --이스케이프문자

 SELECT *
 FROM EMPLOYEES
 WHERE COMMISSION_PCT IS NULL; -- NULL인것만 찾아와라

 SELECT *
 FROM EMPLOYEES
 WHERE COMMISSION_PCT IS NOT NULL; -- NULL이 아닌것만 조회해라

 SELECT *
 FROM EMPLOYEES
 WHERE COMMISSION_PCT = NULL; -- 찾을 수 없기에 기억도 하지 말자
 
   SELECT *
   FROM EMPLOYEES
 WHERE NOT EMPLOYEE_ID >= 200 -- 연산자 순서 
   OR EMPLOYEE_ID  = 100;
 
 SELECT *
   FROM EMPLOYEES
 WHERE NOT (EMPLOYEE_ID >= 200 -- 연산자 순서 ()
   OR EMPLOYEE_ID  = 100); 


-- 부서 테이블
SELECT * FROM DEPARTMENTS; 

-- 직급 테이블
SELECT * FROM JOBS;

-- 국가 테이블
SELECT * FROM COUNTRIES; 

-- 국가별 지역 테이블
SELECT * FROM LOCATIONS; 

-- 대륙 테이블
SELECT * FROM REGIONS; 