CREATE TABLE TB_SYSTEM(
			 ADMIN_NAME_ID		VARCHAR2(30)  PRIMARY KEY
			,PASSWORD           VARCHAR2(30)  NOT NULL
			);
SELECT * FROM TB_SYSTEM;		
DROP TABLE TB_SYSTEM;
CREATE TABLE  TB_CLOTHS (
			 BRAND_CODE		VARCHAR(20)   
			,PRODUCT_CODE	VARCHAR(20)	  PRIMARY KEY
			,PRODUCT_NAME	VARCHAR(30)	  NOT NULL
			,PRICE			NUMBER		  NOT NULL
			,COUNTS	  		NUMBER		  NOT NULL
			,DEL_YN			CHAR(1)		  DEFAULT 'N'
			,REGIST_DT		DATE		  NOT NULL
			);
SELECT * FROM TB_CLOTHS;
DROP TABLE TB_CLOTHS;
CREATE TABLE TB_BRAND(
			 BRAND_CODE		VARCHAR(20)   PRIMARY KEY
			,BRAND_NAME	 	VARCHAR(20)	  NOT NULL
			,ADDRESS		VARCHAR(100)  NOT NULL
			,TEL			VARCHAR(30)	  NOT NULL
			,DEL_YN	  		CHAR(1) 	  DEFAULT 'N'
			,REGIST_DT      DATE		  NOT NULL
			);    
		
SELECT * FROM TB_BRAND;			
DROP TABLE TB_BRAND;

SELECT * 
	FROM TB_BRAND TB
	JOIN TB_CLOTHS TC
	ON TB.BRAND_CODE = TC.BRAND_CODE;


