-- NULL이 있는 경우 오른쪽 값이 나오게 해주는 기능 
SELECT NVL(NULL, 'Default')
FROM DUAL;

SELECT NVL(COMMISSION_PCT,0)
 FROM EMPLOYEES;
 
--식, 값1, 반환값1, 값2, 반환값2, 값3, 반환값3 ..... 기본값(반복후)
-- DECODE(식, 값1, 반환값1, 값2, 반환값2, 값3, 반환값3 ..... 기본값)

SELECT DECODE(DEPARTMENT_ID, 90, 'A부서', 60, 'B부서',100, 'C부서', '그 외' )
FROM EMPLOYEES;

SELECT DECODE(EXTRACT(YEAR FROM HIRE_DATE), 2000, '신규사원', '기존사원') 
	FROM EMPLOYEES;


SELECT SALARY AS 급여 
	,CASE WHEN SALARY >= 2000 AND SALARY < 5000 THEN '하위소득'
			WHEN SALARY >= 5000 AND SALARY < 10000 THEN '중위소득'
			WHEN SALARY >= 10000  THEN '고소득'
			ELSE '미분류'
		END AS 급여분류
FROM EMPLOYEES;
 

--그룹함수
SELECT SUM(SALARY) AS 총합
	  ,AVG(SALARY) AS 평균
	  ,MAX(SALARY) AS 최대급여
	  ,MIN(SALARY) AS 최소급여
	  ,COUNT(SALARY) AS 행수
	FROM EMPLOYEES
WHERE DEPARTMENT_ID = 100;

SELECT *
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 100;

SELECT MAX(FIRST_NAME)
	  ,MIN(LAST_NAME)
FROM EMPLOYEES;

SELECT COUNT(*)
FROM EMPLOYEES;