-- Ctrl + '+'
SELECT 'Hello Oracle Cloud' FROM  DUAL;
/*
*
* admin, system 은 관리자 계정임
*
* 개발자용 사용자 계정으로 데이터베이스를 사용할 수 있도록
*  별도의 계정을 생성
*/

CREATE USER puser2 IDENTIFIED BY puser2;


-- 생성한 계정에 권한 부여
GRANT RESOURCE, CONNECT  TO puser2;
GRANT INSERT  ANY TABLE , UPDATE ANY TABLE
      , DELETE ANY TABLE, CREATE VIEW
      , CREATE SESSION TO puser1;
      
     
-- 테이블 스페이스 사용 권한 및 용량 설정
ALTER USER puser2 quota 10M ON USERS;


SELECT USERNAME FROM ALL_USERS WHERE  USERNAME = 'PUSER2';

SELECT GRANTED_ROLE FROM DBA_ROLE_PRIVS WHERE GRANTEE = 'PUSER2';

SELECT PRIVILEGE FROM DBA_SYS_PRIVS WHERE GRANTEE = 'PUSER2';

SELECT * FROM DBA_USERS WHERE USERNAME = 'PUSER2';

SELECT * FROM EMPLOYEES