-- 사용자 정의 타입
DECLARE
-- 레코드 타입
	TYPE MY_TYPE_RECORD IS RECORD(
	 	 ID		EMPLOYEES.EMPLOYEE_ID%TYPE
		,FNAME 	EMPLOYEES.FIRST_NAME%TYPE
		,LNAME 	EMPLOYEES.LAST_NAME%TYPE
		,SALARY EMPLOYEES.SALARY%TYPE
		,DEPT_NAME DEPARTMENTS.DEPARTMENT_NAME%TYPE
	);
--레코드 타입을 지정
	RECORD_DATA MY_TYPE_RECORD;
BEGIN
	-- 레코드 타입을 지정하면 레코드에 정의한 타입들만 추가하는 형식으로 작성이 가능하다.
	-- 하나의 행 데이터만 조회가 될 수 있도록 작업해라.
	SELECT E.EMPLOYEE_ID
		  ,E.FIRST_NAME
		  ,E.LAST_NAME
		  ,E.SALARY
		  ,D.DEPARTMENT_NAME
	INTO RECORD_DATA
	FROM EMPLOYEES E JOIN DEPARTMENTS D
	ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
	WHERE E.EMPLOYEE_ID = 100;
	
	DBMS_OUTPUT.PUT_LINE(RECORD_DATA.ID);
	DBMS_OUTPUT.PUT_LINE(RECORD_DATA.FNAME);
	DBMS_OUTPUT.PUT_LINE(RECORD_DATA.LNAME);
	DBMS_OUTPUT.PUT_LINE(RECORD_DATA.SALARY);
	DBMS_OUTPUT.PUT_LINE(RECORD_DATA.DEPT_NAME);
END;






-- 사용자 정의 타입2
DECLARE
--		테이블 타입 : 배열이라고 생각하면 된다.
	TYPE MY_TYPE_TABLE IS TABLE OF EMPLOYEES.EMPLOYEE_ID%TYPE INDEX BY BINARY_INTEGER;

	TABLE_DATA   MY_TYPE_TABLE;
	IDX 	NUMBER :=1;
BEGIN
	FOR D IN (SELECT EMPLOYEE_ID FROM EMPLOYEES) LOOP
		TABLE_DATA(IDX) := D.EMPLOYEE_ID;
		IDX := IDX + 1;
	END LOOP;
	
	FOR I IN 1..TABLE_DATA.COUNT LOOP
		DBMS_OUTPUT.PUT_LINE(TABLE_DATA(I));
	END LOOP;
END;






DECLARE
--		테이블 타입 : 배열이라고 생각하면 된다.
	TYPE MY_TYPE_TABLE IS TABLE OF EMPLOYEES%ROWTYPE INDEX BY BINARY_INTEGER;

	TABLE_DATA   MY_TYPE_TABLE;
	IDX 	NUMBER :=1;
BEGIN
	FOR D IN (SELECT * FROM EMPLOYEES) LOOP
		TABLE_DATA(IDX) := D;
		IDX := IDX + 1;
	END LOOP;
	
	FOR I IN 1..TABLE_DATA.COUNT LOOP
		DBMS_OUTPUT.PUT_LINE(TABLE_DATA(I).EMPLOYEE_ID);
	END LOOP;
END;




DECLARE
	-- 레코드 타입
	TYPE MY_TYPE_RECORD IS RECORD(
	 	 ID		EMPLOYEES.EMPLOYEE_ID%TYPE
		,FNAME 	EMPLOYEES.FIRST_NAME%TYPE
		,LNAME 	EMPLOYEES.LAST_NAME%TYPE
		,SALARY EMPLOYEES.SALARY%TYPE
		,DEPT_NAME DEPARTMENTS.DEPARTMENT_NAME%TYPE
	);
	-- 테이블 타입
	TYPE MY_TYPE_TABLE IS TABLE OF MY_TYPE_RECORD INDEX BY BINARY_INTEGER;

	TABLE_DATA   MY_TYPE_TABLE;
	IDX 	NUMBER :=1;
BEGIN
	FOR D IN (SELECT EMPLOYEE_ID 
					,FIRST_NAME
					,LAST_NAME
					,SALARY
					,D.DEPARTMENT_NAME
					FROM EMPLOYEES E JOIN DEPARTMENTS D
						ON E.DEPARTMENT_ID = D.DEPARTMENT_ID) LOOP 
		TABLE_DATA(IDX) := D;
		IDX := IDX + 1;
	END LOOP;
	
	FOR I IN 1..TABLE_DATA.COUNT LOOP
		DBMS_OUTPUT.PUT_LINE(TABLE_DATA(I).ID);
	END LOOP;
END;




